### PR TITLE
Add macOS ARM

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #7

Follow-up to #6
Helpful for https://github.com/conda-forge/conda-forge.github.io/pull/1627

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@isuruf This would be the follow-up to #6

**Review by sstadick — APPROVED** [review]
Topically this all looks fine to me.

My only question / comment is why the build for this is failing still?

**Comment by BastianZim** [comment]
That's what we're trying to figure out...😄

This is the same as the last PR, I just opened it because of merge conflicts and the branch renaming as @isuruf wanted to have a clean PR to work on.

**Comment by sstadick** [comment]
Ahhh, gotcha! Sorry, I thought it was "final form" 👍

**Comment by BastianZim** [comment]
Ahh no sorry this is just because of the merge conflicts.

**Comment by BastianZim** [comment]
It went through 🎉 I know you're very busy so appreciate the help a lot @isuruf !

**Comment by sstadick** [comment]
Awesome! Thanks @BastianZim and @isuruf for getting this working!

Is there anything standing in the way of a squash and merge?

**Comment by BastianZim** [comment]
All good from my side!

**Comment by BastianZim** [comment]
@sstadick I know that Isuru is generally quite busy so, since all checks are passing, I think this can be merged. But also happy to wait longer, if you prefer. :)

**Pull request merged**
